### ISSUE TITLE
Support for mark* methods

### ISSUE THREAD

**Issue by adrianriepl** [ngneat/forms-manager#12]
Would it make sense to add support the `mark*()` methods for a form or a control?

The methods could be called like `formsManager.patchValue()`:

```ts
formsManager.markAllAsTouched('unboarding')

formsManager.markAsDirty('unboarding')

formsManager.markAsPending('unboarding')

formsManager.markAsPristine('unboarding')

formsManager.markAsTouched('unboarding')

formsManager.markAsUntouched('unboarding')
```

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.

**Comment by adrianriepl** [comment]
I tried to implement the mark* methods but I am struggling a little bit. Maybe I made a mistake somewhere or have a misunderstanding how the library is structured. I have the following problem:

- When using `markAllAsTouched()` I'll get the error => `core.js:4117 ERROR TypeError: this._forEachChild is not a function
    at Object.push../node_modules/@angular/forms/__ivy_ngcc__/fesm5/forms.js.AbstractControl.markAllAsTouched (forms.js:2951)`
- When I use a "normal" method such as `markAsDirty()` the property of the control does not change.

Can somebody help me out?

[My fork](https://github.com/adrianriepl/forms-manager)

**Comment by NetanelBasal** [comment]
You can't call https://github.com/adrianriepl/forms-manager/blob/master/projects/ngneat/forms-manager/src/lib/forms-manager.ts#L261. As you said, it is only available since Angular 8.0.0.

**Comment by NetanelBasal** [comment]
You should do something like https://stackoverflow.com/a/44150793/7330592

**Comment by adrianriepl** [comment]
I forked the library after the last commit (where it was changed to Angular 9.1.11) so it should be available already or am I not seeing something?

**Comment by NetanelBasal** [comment]
You are right. When do you see the error?

**Comment by adrianriepl** [comment]
You will see the error when you click on the save button in the demo application. Here I call `this.manager.markAllAsTouched('stepOne')`.

https://github.com/adrianriepl/forms-manager/blob/b6751ba9af2569928439316823d9ef758bac9175/src/app/demo/demo.component.ts#L50

**Comment by NetanelBasal** [comment]
I'll check it later. But try to debug it. Add a debugger statement and see why you get the error.
