### ISSUE TITLE
Add getInitialValue() function to get  the initial form value already stored in forms-manager

### ISSUE THREAD

**Issue by manudss** [ngneat/forms-manager#15]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Cannot get the initial value of form. This was in private. 

## Expected behavior

We would like to be able to obtain the initial value of the form. This value has been saved by the plug-in for the isDirty function. 
It is not possible to retrieve this value, as it is in private property. There is a method called setInitialValue(). It would be useful to have a method: getInitialValue().

/**
   *
   * Get the initial value for a control
   *
   * @example
   *
   * manager.getInitialValue('login');
   *
   */
  getInitialValue(name: keyof FormsState): any {
    return this.initialValues$$.get(name);
  }

## What is the motivation / use case for changing the behavior?

In our case, we would need to retrieve the initial value of the form, in order to make calculations afterwards to calculate the differences and track all the changes that have been made. And, like, we would use this plug-in that would store the initial state. It would be a shame to have to store this state somewhere else, when it's already stored in form-manager, and we could just retrieve it here.  

Is it ok for you to make a pull request to add this feature to the plug-in?

**Comment by NetanelBasal** [comment]
Yes

**Comment by marleypowell** [comment]
Is there a way that I can use this feature or is there a new package version that will be released soon?
