### ISSUE TITLE
Request for enhance setup and basic usage documentation

### ISSUE THREAD

**Issue by Kitefr** [ngneat/forms-manager#19]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am currently using the last version of Akita Store.
I tried to install and use this package as stated on the README file but i got the following error.
```
No provider for NgFormManager.
```
So i added the NgFormManager as a provider in my AppModule. The error disappeared but nothing else happened.

What steps am I missing ?

I saw the package lock is saying the package was made with Angular 9. 
Can it still work for Angular 8 application ?

## Expected behavior

The package work as stated in the README file

## Minimal reproduction of the problem with instructions

Install and use the code from the `Installation` section of the README file.

## What is the motivation / use case for changing the behavior?

Can have the advantage of forms in Akita Store.

## Environment

<pre><code>
Angular version: 8 (core: 8.2.14)

Browser:
- [x] Chrome (desktop) version 85
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  macOS 10.14.6

Others:
None
</code></pre>

**Comment by NetanelBasal** [comment]
You don't need to add it anywhere. Inject it and use it.

**Comment by Kitefr** [comment]
I injected it into my component like every other services but I got the `No provider for NgFormManager` error when I tried to use it like in the example.
Maybe it is not compatible with my version on Angular (v8)

**Comment by NetanelBasal** [comment]
It should work. Can you reproduce it on stackblitz, please?

**Comment by Kitefr** [comment]
Here is is: https://angular-ivy-6qwcyv.stackblitz.io
I do not have the error here. But nothing seems to happen on the store either.

**Comment by NetanelBasal** [comment]
Please attach link to the editor.

**Comment by Kitefr** [comment]
Sorry about that: https://stackblitz.com/edit/angular-ivy-6qwcyv?file=src%2Fmain.ts
Here it is.

**Comment by NetanelBasal** [comment]
It works fine. I can't understand what the issue is? Did you read the docs and understand the purpose of this library?

**Comment by Kitefr** [comment]
Then i might not have understood the purpose of this library.
Nothing show up in my akita store when i make change in a form plugin in with forms-manager.

**Comment by NetanelBasal** [comment]
This library doesn't relate to Akita

**Comment by Kitefr** [comment]
So why is it mentioned in Akita's documentation for form management ?

**Comment by Kitefr** [comment]
I understand now. I am using the old library for now to see it on Akita, i'll make the switch later on when possible to the new library (this one). Thank you for your time.
