### ISSUE TITLE
Slow to update state?

### ISSUE THREAD

**Issue by ivanmayes** [ngneat/forms-manager#21]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a project with akita and the forms-manager.  I feel like I'm using it fairly simply, but there is a noticeable roughly 1 second lag between patching a value and seeing the change manifest down through the .valueChanges observable.  Attached code and behavior video below.  No clue what I could be doing to see such an issue in performance.

## Environment

<pre><code>
Angular version: 9.1.2

Browser:
- [ x] Chrome (desktop) version 86
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

![image](https://user-images.githubusercontent.com/847700/96663878-3d62e900-1317-11eb-98c9-3d3e86ef5152.png)

####Nested component:
![image](https://user-images.githubusercontent.com/847700/96663925-579cc700-1317-11eb-9dc9-1f7307898229.png)
![image](https://user-images.githubusercontent.com/847700/96663960-65eae300-1317-11eb-9ce0-a60d85e20db3.png)
[Screen Recording 2020-10-20 at 9.04.58 PM.mov.zip](https://github.com/ngneat/forms-manager/files/5412796/Screen.Recording.2020-10-20.at.9.04.58.PM.mov.zip)

**Comment by NetanelBasal** [comment]
I think it's because we [apply](https://github.com/ngneat/forms-manager/blob/master/projects/ngneat/forms-manager/src/lib/forms-manager.ts#L382) a `debounceTime`.

**Comment by ivanmayes** [comment]
That was it!  Applying `{ debounceTime: 0 }` fixed the issue.  Thanks!
