### ISSUE TITLE
Initial values not being cleared using blank clear or destroy methods

### ISSUE THREAD

**Issue by adrianriepl** [ngneat/forms-manager#29]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request
- [ ] Other... Please describe:

## Current behavior

When calling the methods `formsManager.clear()` or `formsManager.destroy()` without parameters the existing initial values are not being cleared.

## Expected behavior

Calling `formsManager.clear()` or `formsManager.destroy()` should also clear the `Map` of the initial values (`initialValues$$`).

## What is the motivation / use case for changing the behavior?

So you don't have to call `removeInitialValue(name)` (is actually private) for each set initial value.

**Comment by NetanelBasal** [comment]
Do u want to create a PR?

**Comment by adrianriepl** [comment]
Yes, I can create a PR :thumbsup:
