### ISSUE TITLE
Ivy support

### ISSUE THREAD

**Issue by dams-dev** [ngneat/forms-manager#60]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

show Ivy warning when build with an ivy project
"Encourage the library authors to publish an Ivy distribution"

## Expected behavior

support Ivy

## Minimal reproduction of the problem with instructions

use forms-manager in a new angular13+ project

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR

**Comment by TheSteinn** [comment]
Any chance this can get a new release?

**Comment by NetanelBasal** [comment]
Done
