### ISSUE TITLE
Mat Date Picker value doesn't persist to local storage

### ISSUE THREAD

**Issue by dspeirs7** [ngneat/forms-manager#7]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using a mat date picker the value is an empty object instead of the date selected.

## Expected behavior

The correct date to be stored instead of an empty object.

## Minimal reproduction of the problem with instructions

Add a mat date picker and persist to local storage.

## What is the motivation / use case for changing the behavior?

To have the date persist on refresh.

## Environment

<pre><code>
Angular version: 9.1.9

Browser:
- [X] Chrome (desktop) version 81.0.4044.138
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16.3
- Platform:  Windows

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.
